--- #YAML:1.0
name:                   CPAN-Testers-Data-Uploads-Mailer
version:                0.02
abstract:               Verify CPAN uploads and mails reports
author:
  - Barbie <barbie@cpan.org>

license:                perl
distribution_type:      module
installdirs:            site

requires:
  Email::Simple:        0
  File::Basename:       0
  File::Path:           0
  File::Slurp:          0
  Getopt::ArgvFile:     0
  Getopt::Long:         0
  IO::File:             0
  Template:             0
  Time::Piece:          0

provides:
  CPAN::Testers::Data::Uploads::Mailer:
    file:     lib/CPAN/Testers/Data/Uploads/Mailer.pm
    version:  0.02

no_index:
  directory:
    - t

resources:
  license:    http://dev.perl.org/licenses/
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=CPAN-Testers-Data-Uploads-Mailer
  repository: http://github.com/barbie/cpan-testers-data-uploads-mailer

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Hand 1.0
